# Generated by Django 5.0.6 on 2024-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='healthcare',
            field=models.CharField(blank=True, max_length=167, null=True),
        ),
    ]
