# Generated by Django 5.0.6 on 2024-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_healthfacilities_healthcare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='operatorty',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
