# Generated by Django 5.0.6 on 2024-07-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_healthfacilities_operatorty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='amenity',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
